name: Build Wheels
on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci"]
jobs:
  tests:
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/checkout@v4
      - run: git submodule update --init --recursive bc7enc_rdo
      - name: Run on ${{ matrix.os }}
        run: |
          python -m pip install .[tests]
          python -m pytest

      - uses: actions/upload-artifact@v4
        with:
          name: tests-output-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./tests-output/*.png


  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
      - run: git submodule update --init --recursive bc7enc_rdo

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
