name: Build lib
on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci"]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init --recursive bc7enc_rdo

      #- name: Setup MSBuild environment
      #  shell: cmd
      #  run: |
      #      call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\VsDevCmd.bat"

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build dll
        run: |
            cp CMakeLists.txt bc7enc_rdo/
            cd bc7enc_rdo
            cmake -G "NMake Makefiles" .
            ls
            nmake
            ls
